name: Build and release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  bump-version:
    name: Release version
    runs-on: ubuntu-latest

    steps:
      - uses: GoogleCloudPlatform/release-please-action@v4
        id: release
        with:
          release-type: python
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: release-please-config.yaml
          manifest-file: .release-please-manifest.json
